[tool.poetry]
name = "longcat-recorder"
version = "0.1.0"
description = ""
authors = ["Mark Meliksetyan <markmelix@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
python-dotenv = "^1.0.0"
aiogram = "^3.1.0"
discord-py-self = {git = "https://github.com/dolfies/discord.py-self.git"}
discord-ext-audiorec = {path = "/home/mark/code/forks/discord-ext-audiorec/dist/discord_ext_audiorec-0.1.6-cp311-cp311-linux_x86_64.whl"}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
